Switch to using pgserver for postgres
mkornacker/pixeltable pull request #59
Opened 2024-01-09 19:25 UTC by orm011

This enables pip install in mac to work without extra docker setup (unless they use nos)

2024-01-09 20:12 UTC, mkornacker requested changes

2024-01-09 20:12 UTC, mkornacker commented on pixeltable/env.py
> +        self._inited = False
_initialized

2024-01-09 20:12 UTC, mkornacker commented on pixeltable/env.py
> +        env_pgdata = os.environ.get('PIXELTABLE_PGDATA')
it doesn't look like that's useful beyond accommodating tests, no?

2024-01-09 20:12 UTC, mkornacker commented on pixeltable/env.py
> +    def db_url(self, hide_passwd=False) -> str:
unused parameter

2024-01-09 20:12 UTC, mkornacker commented on pixeltable/env.py
> +        self.db_server = pgserver.get_server(self._pgdata_dir)
_...

2024-01-09 20:12 UTC, mkornacker commented on pixeltable/tests/conftest.py
> +    # NB: unix socket path names cannot exceed ~100 chars,
remove 'NB' (if it's not worth noting, it's not worth having here as a comment; in general, don't add fluff to comments)

2024-01-09 20:12 UTC, mkornacker commented on pixeltable/tests/conftest.py
> +    yield Env.get()
this changes the function signature

2024-01-09 20:12 UTC, mkornacker commented on pixeltable/tests/conftest.py
> +    # Will make a separate dir at a shallower path for testing purposes.
this seems like a general problem. is there no good solution for that? the user may well have a pixeltable home directory that will exceed this threshold.

2024-01-09 20:47 UTC, orm011 reviewed
> *[Reviewable](https://reviewable.io/reviews/mkornacker/pixeltable/59)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/env.py` line 114 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446542515:-NnjvoBsEJn7wriwDbU5:bso9afd) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/env.py#L114)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

it doesn't look like that's useful beyond accommodating tests, no?
</blockquote></details>

correct.
___
*[`pixeltable/env.py` line 154 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446544336:-NnjyKwV8siyOtj2uWxU:b-wudljx) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/env.py#L154)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

_...
</blockquote></details>

not sure what you mean here.
___
*[`pixeltable/tests/conftest.py` line 27 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446545960:-Nnjumq_34hewqnb5tS5:b-896fix) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/tests/conftest.py#L27)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

remove 'NB' (if it's not worth noting, it's not worth having here as a comment; in general, don't add fluff to comments)
</blockquote></details>

Done.
___
*[`pixeltable/tests/conftest.py` line 29 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446550899:-NnjunHoAG0K3wOrJM1c:b-ju6if4) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/tests/conftest.py#L29)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

this seems like a general problem. is there no good solution for that? the user may well have a pixeltable home directory that will exceed this threshold.
</blockquote></details>

There's definitely a solution, changing pgserver to decouple the socket path from the pgdata path.

The main issue with changing pgserver is that builds on github are slow. In the meantime, since the default setup is to use the $HOME/.pixeltable, which is unlikely to be an issue, seems ok to defer. 
___
*[`pixeltable/tests/conftest.py` line 40 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446546907:-Nnjvk8i4Xhmc5JJYLvd:b-igp9nk) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/tests/conftest.py#L40)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

this changes the function signature
</blockquote></details>

removed, not needed in the end


<!-- Sent from Reviewable.io -->

2024-01-09 20:47 UTC, orm011 reviewed
> *[Reviewable](https://reviewable.io/reviews/mkornacker/pixeltable/59)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/env.py` line 59 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446541655:-NnjyeuC6NbCvrw7fFVF:b-896fix) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/env.py#L59)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

_initialized
</blockquote></details>

Done.
___
*[`pixeltable/env.py` line 61 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446542917:-NnjyfQ02J3bhcueF17R:bss4a2b) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/env.py#L61)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

unused parameter
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2024-01-10 02:32 UTC, orm011 reviewed
> *[Reviewable](https://reviewable.io/reviews/mkornacker/pixeltable/59)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/env.py` line 114 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446542515:-NnlCaM-BeyHxWO4UhQz:b64hhbq) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/env.py#L114)):*
<details><summary><i>Previously, orm011 (Oscar Moll) wrote…</i></summary><blockquote>

correct.
</blockquote></details>

no longer a thing, due to change in pgserver.
___
*[`pixeltable/tests/conftest.py` line 29 at r1](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446550899:-NnlCLE66w0VKA-i7j_c:b-k52p3d) ([raw file](https://github.com/mkornacker/pixeltable/blob/5a1a7d84ecacb85632c60af8f45d4c756c4cf33b/pixeltable/tests/conftest.py#L29)):*
<details><summary><i>Previously, orm011 (Oscar Moll) wrote…</i></summary><blockquote>

There's definitely a solution, changing pgserver to decouple the socket path from the pgdata path.

The main issue with changing pgserver is that builds on github are slow. In the meantime, since the default setup is to use the $HOME/.pixeltable, which is unlikely to be an issue, seems ok to defer.
</blockquote></details>

no longer relevant, handled in new pgserver by using a different path for socket.


<!-- Sent from Reviewable.io -->

2024-01-10 02:41 UTC, mkornacker commented on pixeltable/env.py
> +    def db_url(self) -> str:
the other members like tmp_dir are properties, might as well make this one

2024-01-10 02:41 UTC, mkornacker commented on pixeltable/env.py
>      def db_service_url(self) -> str:
do we still need this?

2024-01-10 02:41 UTC, mkornacker commented on pixeltable/env.py
> +        self._pgdata_dir = (self._home / 'pgdata')
only __init__ should create instance members

2024-01-10 02:41 UTC, mkornacker commented on pixeltable/env.py
> +        # we now have a home directory and db; start runtime containers
update comment

2024-01-10 02:41 UTC, mkornacker commented on pixeltable/env.py
> -    def tear_down(self) -> None:
isn't this needed for the tests?

2024-01-10 02:41 UTC, mkornacker commented on pixeltable/tests/conftest.py
> -    # leave db in place for debugging purposes
this comment is useful

2024-01-10 03:02 UTC, orm011 reviewed
> *[Reviewable](https://reviewable.io/reviews/mkornacker/pixeltable/59)* status: 0 of 5 files reviewed, 13 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/env.py` line 0 at r2](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446821441:-NnlFipoAw7OEdedxW0A:b-xpyly5) ([raw file](https://github.com/mkornacker/pixeltable/blob/259c69f4f40accea5ca05b72f01276e068e47576/pixeltable/env.py#L0)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/mkornacker/pixeltable/pull/59#discussion_r1446821441) to the right spot — sorry!)*

isn't this needed for the tests?
</blockquote></details>

it was only called from one place in the code base, I simply inlined that use case.
___
*[`pixeltable/env.py` line 61 at r2](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446819532:-NnlJ0fE-T6jdHgU8Hyr:b-896fix) ([raw file](https://github.com/mkornacker/pixeltable/blob/259c69f4f40accea5ca05b72f01276e068e47576/pixeltable/env.py#L61)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

the other members like tmp_dir are properties, might as well make this one
</blockquote></details>

Done.
___
*[`pixeltable/env.py` line 65 at r2](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446819745:-NnlJ1Yk4d5VEfXZVYLT:b-hfpv0l) ([raw file](https://github.com/mkornacker/pixeltable/blob/259c69f4f40accea5ca05b72f01276e068e47576/pixeltable/env.py#L65)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

do we still need this?
</blockquote></details>

removed
___
*[`pixeltable/env.py` line 113 at r2](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446820299:-NnlJ3-A1u2SPfglnXSc:bb7f2mf) ([raw file](https://github.com/mkornacker/pixeltable/blob/259c69f4f40accea5ca05b72f01276e068e47576/pixeltable/env.py#L113)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

only __init__ should create instance members
</blockquote></details>

done
___
*[`pixeltable/env.py` line 177 at r2](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446821114:-NnlJ5qQ4GfSk0HNqltQ:b-mj3fma) ([raw file](https://github.com/mkornacker/pixeltable/blob/259c69f4f40accea5ca05b72f01276e068e47576/pixeltable/env.py#L177)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

update comment
</blockquote></details>

isnt the comment still relevant and accurate? 
___
*[`pixeltable/tests/conftest.py` line 0 at r2](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446821664:-NnlJN4_Dn_2NfW2mmKu:boquah9) ([raw file](https://github.com/mkornacker/pixeltable/blob/259c69f4f40accea5ca05b72f01276e068e47576/pixeltable/tests/conftest.py#L0)):*
<details><summary><i>Previously, mkornacker (Marcel Kornacker) wrote…</i></summary><blockquote>

*(Reviewable was [unable](https://github.com/Reviewable/Reviewable/issues/14) to map [this GitHub inline comment thread](https://github.com/mkornacker/pixeltable/pull/59#discussion_r1446821664) to the right spot — sorry!)*

this comment is useful
</blockquote></details>

restored. 


<!-- Sent from Reviewable.io -->

2024-01-10 03:09 UTC, orm011 reviewed
> *[Reviewable](https://reviewable.io/reviews/mkornacker/pixeltable/59)* status: 0 of 5 files reviewed, 13 unresolved discussions (waiting on @mkornacker)

___
*[`pixeltable/env.py` line 113 at r2](https://reviewable.io/reviews/mkornacker/pixeltable/59#gh-1446820299:-NnlKjfd2seyvZpKpWrl:b-fh7hc8) ([raw file](https://github.com/mkornacker/pixeltable/blob/259c69f4f40accea5ca05b72f01276e068e47576/pixeltable/env.py#L113)):*
<details><summary><i>Previously, orm011 (Oscar Moll) wrote…</i></summary><blockquote>

done
</blockquote></details>

ps. can we just set up ruff for linting? this kind of stuff makes no difference to customers, and just represented another iteration pushing and testing... and tests work either way. makes python dev much slower.


<!-- Sent from Reviewable.io -->

2024-01-10 05:08 UTC, mkornacker approved these changes

2024-01-10 18:55 UTC, closed without merging